In [46]:
import pandas as pd
import plotly.express as px

In [47]:
df = pd.read_csv('..\\dataset\\ecommerce_sales_analytics_5000.csv')

## data analysis

In [48]:
df.sample(10)

,order_id,order_date,customer_id,product_category,region,quantity,unit_price,discount,payment_method,delivery_days,customer_rating,revenue
4882,14883,5/15/2035,1839,Clothing,East,7,466.86,0.10,COD,4,1.5,2941.22
685,10686,11/17/2023,1791,Electronics,East,5,291.39,0.04,Card,3,2.3,1398.67
3559,13560,9/30/2031,1189,Electronics,South,7,63.09,0.11,COD,7,2.1,393.05
2900,12901,12/10/2029,1304,Clothing,East,4,562.18,0.11,Card,7,2.0,2001.36
474,10475,4/20/2023,1744,Clothing,West,6,208.26,0.33,Card,6,4.9,837.21
2251,12252,3/1/2028,1421,Electronics,South,2,355.44,0.16,Wallet,6,3.0,597.14
4515,14516,5/13/2034,1331,Clothing,South,2,365.91,0.01,Card,7,2.8,724.50
2003,12004,6/27/2027,1994,Electronics,North,1,447.12,0.12,Wallet,8,1.5,393.47
4933,14934,7/5/2035,1548,Electronics,East,2,451.66,0.25,COD,10,1.4,677.49
836,10837,4/16/2024,1953,Home,East,5,152.21,0.05,COD,10,3.5,723.00

In [49]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          5000 non-null   int64
 1   order_date        5000 non-null   str
 2   customer_id       5000 non-null   int64
 3   product_category  5000 non-null   str
 4   region            5000 non-null   str
 5   quantity          5000 non-null   int64
 6   unit_price        5000 non-null   float64
 7   discount          5000 non-null   float64
 8   payment_method    5000 non-null   str
 9   delivery_days     5000 non-null   int64
 10  customer_rating   5000 non-null   float64
 11  revenue           5000 non-null   float64
dtypes: float64(4), int64(4), str(4)
memory usage: 468.9 KB

In [50]:
df[df.duplicated()]  # 0 row
# df[df['order_id'].duplicated()] # 0 row

Empty DataFrame
Columns: [order_id, order_date, customer_id, product_category, region, quantity, unit_price, discount, payment_method, delivery_days, customer_rating, revenue]
Index: []

In [51]:
df['order_date'] = pd.to_datetime(df['order_date'])

In [52]:
df['month'] = df['order_date'].dt.month_name()

In [53]:
df['year_quarter'] = df['order_date'].dt.quarter

In [54]:
df['year'] = df['order_date'].dt.year

In [55]:
df['product_category'] = df['product_category'].astype(str).str.strip()
df['region'] = df['region'].astype(str).str.strip()
df['payment_method'] = df['payment_method'].astype(str).str.strip()

In [56]:
df = df[df['quantity']>0]

In [57]:
df = df[df['delivery_days'] > 0]

In [58]:
df.info()
# df.sample(2)

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          5000 non-null   int64
 1   order_date        5000 non-null   datetime64[us]
 2   customer_id       5000 non-null   int64
 3   product_category  5000 non-null   str
 4   region            5000 non-null   str
 5   quantity          5000 non-null   int64
 6   unit_price        5000 non-null   float64
 7   discount          5000 non-null   float64
 8   payment_method    5000 non-null   str
 9   delivery_days     5000 non-null   int64
 10  customer_rating   5000 non-null   float64
 11  revenue           5000 non-null   float64
 12  month             5000 non-null   str
 13  year_quarter      5000 non-null   int32
 14  year              5000 non-null   int32
dtypes: datetime64[us](1), float64(4), int32(2), int64(4), str(4)
memory usage: 547.0 KB

In [59]:
df.groupby('year').agg({'revenue':'sum', 'quantity':'sum'}).sort_values(by=['revenue'], ascending=False)

        revenue  quantity
year
2033  408725.72      1524
2030  387884.46      1500
2032  386584.63      1492
2026  386369.69      1478
2027  386151.91      1546
2028  376844.80      1476
2022  371824.30      1469
2023  365915.79      1497
2031  365250.83      1427
2034  363239.55      1431
2024  363209.13      1489
2029  359239.24      1472
2025  349802.33      1410
2035  238733.36      1013

In [60]:
df.groupby('month').agg({'revenue':'sum', 'quantity':'sum'}).sort_values(by=['revenue'], ascending=False)

             revenue  quantity
month
May        479772.55      1835
August     460874.78      1738
June       442941.58      1752
July       440570.72      1750
January    426374.92      1772
March      425050.52      1750
February   413890.24      1571
November   410657.88      1629
October    407873.12      1642
September  402368.11      1591
December   400686.16      1539
April      398715.16      1655

In [61]:
df.groupby('year_quarter').agg({'revenue':'sum', 'quantity':'sum'}).sort_values(by=['revenue'], ascending=False)

                 revenue  quantity
year_quarter
2             1321429.29      5242
3             1303813.61      5079
1             1265315.68      5093
4             1219217.16      4810

In [62]:
df.groupby('customer_id').agg({'order_id':'count'}).sort_values(by=['order_id'], ascending=False)

             order_id
customer_id
1663               14
1957               12
1928               12
1935               12
1112               12
...               ...
1023                1
1978                1
1005                1
1964                1
1999                1

[989 rows x 1 columns]

In [63]:
df.groupby('customer_id').agg({'revenue':'sum'}).sort_values(by=['revenue'], ascending=False)

              revenue
customer_id
1663         17680.69
1955         16265.15
1675         15036.46
1276         15023.71
1647         14894.97
...               ...
1715           255.12
1350           254.25
1809           231.68
1109           172.33
1705           119.06

[989 rows x 1 columns]

In [64]:
df.groupby('product_category').agg({'revenue':'sum'}).sort_values(by=['revenue'], ascending=False)

                     revenue
product_category
Electronics       1829899.22
Clothing          1531931.72
Home               982083.92
Beauty             765860.88

In [65]:
df.pivot_table(index=['year','product_category'], columns='year_quarter', values='revenue', aggfunc=sum).reset_index()

year_quarter  year product_category         1         2         3         4
0             2022           Beauty  14577.58  10927.69  16734.73  12264.02
1             2022         Clothing  26966.49  33525.38  23292.70  23093.05
2             2022      Electronics  34706.83  35556.64  29931.59  31616.06
3             2022             Home  19592.16  22248.82  16704.74  20085.82
4             2023           Beauty  14843.69  16115.33  14016.36  11731.58
5             2023         Clothing  21901.44  21942.92  23516.95  31155.22
6             2023      Electronics  25846.69  39220.88  30572.88  29158.43
7             2023             Home  32527.10  16388.09  22731.30  14246.93
8             2024           Beauty  13034.58  17159.23  11761.77  11409.37
9             2024         Clothing  18100.77  23945.56  27572.35  32700.12
10            2024      Electronics  33495.90  23927.32  44578.81  30419.73
11            2024             Home  27213.35  21789.59  13788.79  12311.89
12            2025           Beauty  15001.61   6395.33  10830.16   8552.01
13            2025         Clothing  19352.52  25189.12  27756.91  28968.62
14            2025      Electronics  30351.53  31383.43  38946.70  32560.05
15            2025             Home  18783.94  18361.01  23418.12  13951.27
16            2026           Beauty  11449.84  10603.81  17203.27   9023.48
17            2026         Clothing  21255.56  26293.76  41162.66  42256.58
18            2026      Electronics  29095.92  37988.82  32690.61  29662.14
19            2026             Home  24205.76  17428.39  17398.26  18650.83
20            2027           Beauty  15174.82  10559.93  14717.80  22530.37
21            2027         Clothing  38453.95  33732.42  18828.19  25021.36
22            2027      Electronics  27471.74  35313.81  39330.21  29672.76
23            2027             Home  16417.25  14981.20  31371.06  12575.04
24            2028           Beauty  13896.17  16590.02   9783.01  10166.50
25            2028         Clothing  14709.78  25812.28  28483.69  39901.54
26            2028      Electronics  43624.82  45539.38  27346.23  29782.64
27            2028             Home  11212.02  14488.15  26406.44  19102.13
28            2029           Beauty  17989.36  13342.19  20714.39  12803.68
29            2029         Clothing  27905.08  35347.05  30392.52  18383.56
30            2029      Electronics  25716.44  39782.88  26090.45  30900.28
31            2029             Home  19635.20  15052.49   6707.38  18476.29
32            2030           Beauty   9364.73  12675.95  15671.72  18008.93
33            2030         Clothing  29009.03  18678.85  28180.45  28103.96
34            2030      Electronics  25788.74  46793.57  30678.23  48279.29
35            2030             Home  17339.42  26074.58  13237.21  19999.80
36            2031           Beauty   9004.12  10958.11  13180.61   8954.55
37            2031         Clothing  35336.61  25689.55  30830.50  27522.78
38            2031      Electronics  35491.72  32618.94  29762.82  37646.84
39            2031             Home  18798.83  21990.84  13483.37  13980.64
40            2032           Beauty  18149.35   8783.30  22747.89  13490.07
41            2032         Clothing  29652.49  34574.45  36445.57  25735.65
42            2032      Electronics  24662.23  32511.14  27039.81  41649.58
43            2032             Home  20096.06  20133.15   9231.54  21682.35
44            2033           Beauty  11202.23  21050.78  24277.00  21944.29
45            2033         Clothing  26117.58  18039.07  25830.82  35299.46
46            2033      Electronics  33410.66  45757.51  39997.44  38110.74
47            2033             Home  18698.48  17209.64  15673.72  16106.30
48            2034           Beauty  10474.84  16862.47  21783.53  17185.29
49            2034         Clothing  23060.49  33059.64  35664.77  23552.37
50            2034      Electronics  27825.10  27117.44  31344.13  40026.89
51            2034             Home  23228.54   7530.02  15720.00   8804.03
52            2035           Beauty  11159.33   8468.87   8559.24       NaN
53            2035         Clothing  36436.47  29041.52  19149.54       NaN
54            2035      Electronics  31679.08  31358.44  18066.28       NaN
55            2035             Home  14819.66  17518.54  12476.39       NaN

In [66]:
df.pivot_table(index=['year', 'product_category'], columns='region', values='revenue', aggfunc=sum).reset_index()

region  year product_category      East     North     South      West
0       2022           Beauty  18699.38  11963.27  11002.97  12838.40
1       2022         Clothing  29864.16  23834.38  20976.25  32202.83
2       2022      Electronics  24482.89  54316.88  25890.85  27120.50
3       2022             Home  10186.45  27569.57  20657.83  20217.69
4       2023           Beauty  11606.27  14092.83  15840.98  15166.88
5       2023         Clothing  31922.02  16375.20  23606.58  26612.73
6       2023      Electronics  38731.28  38907.81  25526.43  21633.36
7       2023             Home  22662.70  20482.21  17609.46  25139.05
8       2024           Beauty   9529.69  13076.44  18801.66  11957.16
9       2024         Clothing  17663.35  22821.60  26795.07  35038.78
10      2024      Electronics  46099.91  32943.99  32273.86  21104.00
11      2024             Home  20394.08  15902.40  20443.41  18363.73
12      2025           Beauty  13569.81  10178.99   8357.04   8673.27
13      2025         Clothing  13036.98  31266.02  31538.11  25426.06
14      2025      Electronics  27984.95  36906.03  33029.72  35321.01
15      2025             Home  20268.64  11470.74  19021.17  23753.79
16      2026           Beauty  13403.88  14640.68  12856.00   7379.84
17      2026         Clothing  31789.83  30764.10  18160.04  50254.59
18      2026      Electronics  25121.39  26816.26  31557.08  45942.76
19      2026             Home  29719.83  18190.34  10350.39  19422.68
20      2027           Beauty  22745.12  21542.37   7775.04  10920.39
21      2027         Clothing  27151.12  25305.21  27379.68  36199.91
22      2027      Electronics  33527.00  38826.37  30631.50  28803.65
23      2027             Home  20892.80  17376.44  15332.46  21742.85
24      2028           Beauty  10967.25  10034.68  13641.13  15792.64
25      2028         Clothing  32853.68  15695.45  20198.63  40159.53
26      2028      Electronics  21859.87  40904.74  37912.23  45616.23
27      2028             Home  15157.50  21636.99  19624.26  14789.99
28      2029           Beauty  14866.43  13055.02  14595.71  22332.46
29      2029         Clothing  37339.94  23212.25  27778.12  23697.90
30      2029      Electronics  22099.20  35780.88  28199.87  36410.10
31      2029             Home  19314.26  15818.71  14282.93  10455.46
32      2030           Beauty  15146.67  16073.13  15424.37   9077.16
33      2030         Clothing  19348.65  37318.84  16056.53  31248.27
34      2030      Electronics  33882.19  32107.95  52484.68  33065.01
35      2030             Home  21036.77  17642.82  14961.61  23009.81
36      2031           Beauty   7987.30  13446.41   4408.55  16255.13
37      2031         Clothing  30235.39  31895.42  33838.44  23410.19
38      2031      Electronics  37112.85  21466.66  38373.48  38567.33
39      2031             Home  19444.65  12654.33  17370.88  18783.82
40      2032           Beauty  10396.40  13056.61  20074.24  19643.36
41      2032         Clothing  29967.88  43258.83  22944.29  30237.16
42      2032      Electronics  34944.74  25772.62  40649.43  24495.97
43      2032             Home  19720.48  13628.27  22176.65  15617.70
44      2033           Beauty  13194.80  15848.28  27777.02  21654.20
45      2033         Clothing  30231.12  20850.51  30136.26  24069.04
46      2033      Electronics  29147.14  43936.71  49181.18  35011.32
47      2033             Home  16214.63  27779.03   8577.78  15116.70
48      2034           Beauty   6697.19  11086.67  15470.03  33052.24
49      2034         Clothing  37509.57  25461.88  29202.62  23163.20
50      2034      Electronics  20454.03  34016.33  28316.03  43527.17
51      2034             Home   7029.38  18983.47  10912.63  18357.11
52      2035           Beauty   6098.92   8117.94   5049.24   8921.34
53      2035         Clothing  33668.91  16599.74  19752.52  14606.36
54      2035      Electronics  16355.91   9747.70  33029.34  21970.85
55      2035             Home   4707.00  19049.45   8826.64  12231.50

In [67]:
df.pivot_table(index=['year', 'product_category'], columns='region', values='order_id', aggfunc='count').reset_index()

region  year product_category  East  North  South  West
0       2022           Beauty    24     10     10     9
1       2022         Clothing    29     26     23    29
2       2022      Electronics    26     49     26    29
3       2022             Home    11     23     18    23
4       2023           Beauty     8     15     11    15
5       2023         Clothing    32     22     24    30
6       2023      Electronics    40     39     27    23
7       2023             Home    27     17     17    18
8       2024           Beauty     7     15     16    11
9       2024         Clothing    22     26     31    27
10      2024      Electronics    38     32     35    24
11      2024             Home    26     16     19    21
12      2025           Beauty    12     15      8    11
13      2025         Clothing    21     32     27    25
14      2025      Electronics    31     37     34    31
15      2025             Home    23     13     20    25
16      2026           Beauty    11     13     14     8
17      2026         Clothing    30     32     24    39
18      2026      Electronics    36     25     29    36
19      2026             Home    21     18     12    17
20      2027           Beauty    19     19      7    10
21      2027         Clothing    25     26     30    27
22      2027      Electronics    31     37     22    36
23      2027             Home    22     24     14    16
24      2028           Beauty     9     12     15    18
25      2028         Clothing    31     21     24    32
26      2028      Electronics    30     33     35    43
27      2028             Home    12     17     17    17
28      2029           Beauty    13     15     15    19
29      2029         Clothing    32     30     25    25
30      2029      Electronics    26     38     32    34
31      2029             Home    17     15     16    13
32      2030           Beauty    13     15     15    12
33      2030         Clothing    22     31     19    28
34      2030      Electronics    25     34     48    27
35      2030             Home    19     14     18    25
36      2031           Beauty    12     15      4    17
37      2031         Clothing    29     24     30    31
38      2031      Electronics    40     23     29    42
39      2031             Home    18     15     17    19
40      2032           Beauty    13     13     17    15
41      2032         Clothing    25     38     29    31
42      2032      Electronics    26     29     38    22
43      2032             Home    18     16     16    20
44      2033           Beauty    11     13     22    16
45      2033         Clothing    29     19     33    21
46      2033      Electronics    31     39     38    34
47      2033             Home    13     19     10    17
48      2034           Beauty     6     15     13    23
49      2034         Clothing    37     29     27    27
50      2034      Electronics    20     34     33    37
51      2034             Home    12     21     11    20
52      2035           Beauty     7      9      5     8
53      2035         Clothing    31     22     19    21
54      2035      Electronics    18     13     29    24
55      2035             Home    10     14     11    11

In [68]:
df.pivot_table(index=['product_category'], columns='year', values='order_id', aggfunc='count').reset_index()

# Customers consistently prefer Electronics over other categories :- Increase inventory allocation for Electronics and introduce premium product variants
# Beauty contributes the least to total unit sales :- Investigate pricing , Consider bundling Beauty products with high-selling categories.
# Sales fluctuate from year to year :- month by month analysis may help here to find sale trend

year,product_category,2022,2023,2024,2025,2026,2027,2028,2029,2030,2031,2032,2033,2034,2035
0,Beauty,53,49,49,46,46,55,54,62,55,48,58,62,57,29
1,Clothing,107,108,106,105,125,108,108,112,100,114,123,102,120,93
2,Electronics,130,129,129,133,126,126,141,130,134,134,115,142,124,84
3,Home,75,79,82,81,68,76,63,61,76,69,70,59,64,46

In [69]:
df.groupby('product_category').agg({'customer_rating':'mean', 'delivery_days':'mean'}).round(2)

# customer rating is very low specially for electronic and home :- Conduct customer feedback analysis and review product quality, delivery experience, and after-sales support to identify the root causes of dissatisfaction.

# delivery days are average but can be reduced

                  customer_rating  delivery_days
product_category
Beauty                       3.01           6.20
Clothing                     3.01           6.12
Electronics                  2.95           6.07
Home                         2.94           6.15

In [70]:
df.groupby('payment_method')['order_id'].count()

payment_method
COD       1774
Card      2270
Wallet     956
Name: order_id, dtype: int64